[tool.poetry]
name = "beets-bandcamp"
version = "0.2.0-a0"
description = "Plugin for beets (http://beets.io) to use bandcamp as an autotagger source."
authors = ["Ariel George <unarbolito@gmail.com>", "Šarūnas Nejus <snejus@pm.me>"]
readme = "README.rst"
license = "GPL-2.0"
homepage = "https://github.com/snejus/beets-bandcamp"
repository = "https://github.com/snejus/beets-bandcamp"

packages = [{ include = "beetsplug" }]
include = ["README.rst"]

[tool.poetry.dependencies]
python = "^3.6"

beautifulsoup4 = "*"
beets = ">=1.4.6"
requests = "*"
six = ">=1.9"

[tool.poetry.dev-dependencies]
pytest = "*"
coverage = "^5.3"
pytest-cov = "^2.10.1"

[tool.coverage.run]
branch = true
dynamic_context = "test_function"
source = ["beetsplug"]

[tool.coverage.report]
precision = 2
exclude_lines = [
    "pragma: no cover",
    "if TYPE_CHECKING",
    "if typing.TYPE_CHECKING",
    "raise AssertionError",
    "raise NotImplementedError"
]

[tool.coverage.html]
show_contexts = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
