[tool.poetry]
name = "beets-bandcamp"
version = "0.2.0"
description = "Plugin for beets (http://beets.io) to use bandcamp as an autotagger source."
authors = ["Ariel George <unarbolito@gmail.com>", "Šarūnas Nejus <snejus@pm.me>"]
readme = "README.rst"
license = "GPL-2.0"
homepage = "https://github.com/snejus/beets-bandcamp"
repository = "https://github.com/snejus/beets-bandcamp"

packages = [{ include = "beetsplug" }]
include = ["README.rst"]

[tool.poetry.dependencies]
python = "^3.6"

dataclasses = "*"
beets = ">=1.4.6"
requests = "*"
six = ">=1.9"

[tool.poetry.dev-dependencies]
pytest = "*"
coverage = "^5.3"
pytest-cov = "^2.10.1"
mypy = "^0.790"
flake8 = "^3.8.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
