---
name: Code quality
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test-pythons:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # python: [3.6, 3.7, 3.8, 3.9, "3.10"]
        # beets: [1.4.9, 1.5.0, 1.6.0]
        python: [3.6]
        beets: [1.6.0]
    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Generate requirements.txt
        run: ./generate_requirements
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install . beets==${{ matrix.beets }}
      - name: Pytest
        run: |
          pytest -k 'not need_connection'
      # - name: Coveralls
      #   run: |
      #     pip install coveralls
      #     coveralls
      #   env:
      #     COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      # - name: Flake8
      #   run: poetry run flake8 . --output-file flake.log  --exit-zero
      # - name: Pylint
      #   run: poetry run pylint --output pylint.log --exit-zero beetsplug/**/*.py
      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
