---
name: Code quality
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        beets: ["1.4.9", "1.5.0", "1.6.0"]
    steps:
      - uses: actions/checkout@v3
      - name: Generate requirements.txt
        run: |
          ./generate_requirements
          echo coveralls==3.3.1 >> requirements.txt
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install . beets==${{ matrix.beets }}
      - name: Pytest
        run: pytest -k 'not need_connection'
      - name: Upload coverage data to coveralls.io
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: python${{ matrix.python }}_beets${{ matrix.beets }}
          COVERALLS_PARALLEL: true
      - uses: actions/upload-artifact@master
        with:
          name: coverage
          path: .reports/coverage.xml
  coveralls:
    if: ${{ always() }}
    name: Indicate completion to coveralls.io
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Finished
        run: |
          pip3 install --upgrade coveralls
          coveralls --service=github --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # lint-report:
  #   if: ${{ always() }}
  #   needs: test-pythons
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         # Disabling shallow clone is recommended for improving relevancy of reporting
  #         fetch-depth: 0
  #     - uses: actions/download-artifact@master
  #       with:
  #         name: coverage
  #         path: .reports/coverage.xml
  #     - name: Set up Python ${{ matrix.python }}
  #       uses: actions/setup-python@v3
  #       with:
  #         python-version: "3.10"
  #     - name: Coveralls
  #       run: |
  #         pip install coveralls
  #         coveralls
  #       env:
  #         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      # - name: Flake8
      #   run: poetry run flake8 . --output-file flake.log  --exit-zero
      # - name: Pylint
      #   run: poetry run pylint --output pylint.log --exit-zero beetsplug/**/*.py
      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
